import { Injectable } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { HotelAdmins } from '../../hotel-admins/hotelAdmins.entity';
import { BaseSeeder } from '../base/base.seeder';
import * as bcrypt from 'bcrypt';

@Injectable()
export class HotelAdminSeeder extends BaseSeeder<HotelAdmins> {
  constructor(
    @InjectRepository(HotelAdmins)
    repository: Repository<HotelAdmins>,
  ) {
    super(repository);
  }

  getName(): string {
    return 'HotelAdminSeeder';
  }

  async seed(): Promise<void> {
    const hashedPassword = await bcrypt.hash('HotelAdmin123!', 10);

    const hotelAdmins = [
      // Colombia
      {
        name: 'Carlos',
        lastName: 'Rodriguez',
        email: 'carlos.rodriguez@hotelpalace.com',
        password: hashedPassword,
        phone: '+57 300 123 4567',
        country: 'Colombia',
        city: 'Bogotá',
        address: 'Carrera 13 #26-62',
        birthDate: '1985-03-15',
        numberOfHotels: 0,
        isAdmin: true,
      },
      {
        name: 'Maria',
        lastName: 'Gonzalez',
        email: 'maria.gonzalez@granhotel.com',
        password: hashedPassword,
        phone: '+57 301 987 6543',
        country: 'Colombia',
        city: 'Medellín',
        address: 'Carrera 70 #52-20',
        birthDate: '1990-07-22',
        numberOfHotels: 0,
        isAdmin: true,
      },
      {
        name: 'Luis',
        lastName: 'Martinez',
        email: 'luis.martinez@coastalresort.com',
        password: hashedPassword,
        phone: '+57 302 456 7890',
        country: 'Colombia',
        city: 'Cartagena',
        address: 'Avenida San Martín #45-12',
        birthDate: '1988-11-08',
        numberOfHotels: 0,
        isAdmin: true,
      },
      {
        name: 'Ana',
        lastName: 'Torres',
        email: 'ana.torres@mountainlodge.com',
        password: hashedPassword,
        phone: '+57 303 789 0123',
        country: 'Colombia',
        city: 'Manizales',
        address: 'Carrera 25 #64-30',
        birthDate: '1987-05-14',
        numberOfHotels: 0,
        isAdmin: true,
      },
      // México
      {
        name: 'Diego',
        lastName: 'Hernandez',
        email: 'diego.hernandez@hotelesmx.com',
        password: hashedPassword,
        phone: '+52 55 1234 5678',
        country: 'México',
        city: 'Ciudad de México',
        address: 'Reforma 222, Col. Juárez',
        birthDate: '1986-09-20',
        numberOfHotels: 0,
        isAdmin: true,
      },
      {
        name: 'Sofia',
        lastName: 'Ramirez',
        email: 'sofia.ramirez@cancunhotels.com',
        password: hashedPassword,
        phone: '+52 998 765 4321',
        country: 'México',
        city: 'Cancún',
        address: 'Blvd Kukulcan Km 12.5',
        birthDate: '1992-04-18',
        numberOfHotels: 0,
        isAdmin: true,
      },
      {
        name: 'Roberto',
        lastName: 'Sanchez',
        email: 'roberto.sanchez@gdlhotels.com',
        password: hashedPassword,
        phone: '+52 33 8765 4321',
        country: 'México',
        city: 'Guadalajara',
        address: 'Av. Americas 1500',
        birthDate: '1984-12-05',
        numberOfHotels: 0,
        isAdmin: true,
      },
      // Argentina
      {
        name: 'Lucia',
        lastName: 'Fernandez',
        email: 'lucia.fernandez@buenosaireshotels.com',
        password: hashedPassword,
        phone: '+54 11 4567 8901',
        country: 'Argentina',
        city: 'Buenos Aires',
        address: 'Av. Corrientes 1234',
        birthDate: '1989-06-30',
        numberOfHotels: 0,
        isAdmin: true,
      },
      {
        name: 'Martin',
        lastName: 'Lopez',
        email: 'martin.lopez@mendozahotels.com',
        password: hashedPassword,
        phone: '+54 261 234 5678',
        country: 'Argentina',
        city: 'Mendoza',
        address: 'San Martin 1050',
        birthDate: '1991-01-25',
        numberOfHotels: 0,
        isAdmin: true,
      },
      {
        name: 'Valentina',
        lastName: 'Silva',
        email: 'valentina.silva@cordobahotels.com',
        password: hashedPassword,
        phone: '+54 351 987 6543',
        country: 'Argentina',
        city: 'Córdoba',
        address: 'Av. Colon 520',
        birthDate: '1993-08-12',
        numberOfHotels: 0,
        isAdmin: true,
      },
      // Perú
      {
        name: 'Ricardo',
        lastName: 'Vargas',
        email: 'ricardo.vargas@limahotels.com',
        password: hashedPassword,
        phone: '+51 1 234 5678',
        country: 'Perú',
        city: 'Lima',
        address: 'Av. Larco 1301, Miraflores',
        birthDate: '1987-11-03',
        numberOfHotels: 0,
        isAdmin: true,
      },
      {
        name: 'Carmen',
        lastName: 'Flores',
        email: 'carmen.flores@cuscohotels.com',
        password: hashedPassword,
        phone: '+51 84 765 4321',
        country: 'Perú',
        city: 'Cusco',
        address: 'Plaza de Armas 234',
        birthDate: '1990-03-28',
        numberOfHotels: 0,
        isAdmin: true,
      },
      // Chile
      {
        name: 'Gonzalo',
        lastName: 'Rojas',
        email: 'gonzalo.rojas@santiagohotels.com',
        password: hashedPassword,
        phone: '+56 2 2345 6789',
        country: 'Chile',
        city: 'Santiago',
        address: 'Av. Providencia 1234',
        birthDate: '1988-07-19',
        numberOfHotels: 0,
        isAdmin: true,
      },
      {
        name: 'Francisca',
        lastName: 'Morales',
        email: 'francisca.morales@valparaisohotels.com',
        password: hashedPassword,
        phone: '+56 32 876 5432',
        country: 'Chile',
        city: 'Valparaíso',
        address: 'Paseo 21 de Mayo 45',
        birthDate: '1994-02-14',
        numberOfHotels: 0,
        isAdmin: true,
      },
      // Brasil
      {
        name: 'Paulo',
        lastName: 'Santos',
        email: 'paulo.santos@riohotels.com',
        password: hashedPassword,
        phone: '+55 21 3456 7890',
        country: 'Brasil',
        city: 'Rio de Janeiro',
        address: 'Av. Atlântica 1702, Copacabana',
        birthDate: '1986-10-08',
        numberOfHotels: 0,
        isAdmin: true,
      },
      {
        name: 'Gabriela',
        lastName: 'Costa',
        email: 'gabriela.costa@saopaulohotels.com',
        password: hashedPassword,
        phone: '+55 11 9876 5432',
        country: 'Brasil',
        city: 'São Paulo',
        address: 'Av. Paulista 1578',
        birthDate: '1991-05-22',
        numberOfHotels: 0,
        isAdmin: true,
      },
      // Ecuador
      {
        name: 'Fernando',
        lastName: 'Mendoza',
        email: 'fernando.mendoza@quitohotels.com',
        password: hashedPassword,
        phone: '+593 2 234 5678',
        country: 'Ecuador',
        city: 'Quito',
        address: 'Av. Amazonas N24-03',
        birthDate: '1989-12-17',
        numberOfHotels: 0,
        isAdmin: true,
      },
      {
        name: 'Isabella',
        lastName: 'Castro',
        email: 'isabella.castro@guayaquilhotels.com',
        password: hashedPassword,
        phone: '+593 4 567 8901',
        country: 'Ecuador',
        city: 'Guayaquil',
        address: 'Malecón 2000',
        birthDate: '1992-09-09',
        numberOfHotels: 0,
        isAdmin: true,
      },
      // Costa Rica
      {
        name: 'Andres',
        lastName: 'Jimenez',
        email: 'andres.jimenez@sanjosehotels.com',
        password: hashedPassword,
        phone: '+506 2234 5678',
        country: 'Costa Rica',
        city: 'San José',
        address: 'Paseo Colon, Avenida 2',
        birthDate: '1990-04-05',
        numberOfHotels: 0,
        isAdmin: true,
      },
      {
        name: 'Camila',
        lastName: 'Vega',
        email: 'camila.vega@tamarindohotels.com',
        password: hashedPassword,
        phone: '+506 2654 3210',
        country: 'Costa Rica',
        city: 'Tamarindo',
        address: 'Playa Tamarindo',
        birthDate: '1993-11-20',
        numberOfHotels: 0,
        isAdmin: true,
      },
      // Panamá
      {
        name: 'Alberto',
        lastName: 'Ortega',
        email: 'alberto.ortega@panamahotels.com',
        password: hashedPassword,
        phone: '+507 6234 5678',
        country: 'Panamá',
        city: 'Ciudad de Panamá',
        address: 'Calle 50, Bella Vista',
        birthDate: '1987-08-15',
        numberOfHotels: 0,
        isAdmin: true,
      },
      // Uruguay
      {
        name: 'Natalia',
        lastName: 'Perez',
        email: 'natalia.perez@montevideohotels.com',
        password: hashedPassword,
        phone: '+598 2 234 5678',
        country: 'Uruguay',
        city: 'Montevideo',
        address: 'Rambla República Argentina 1234',
        birthDate: '1991-06-28',
        numberOfHotels: 0,
        isAdmin: true,
      },
    ];

    await this.createIfNotExists(hotelAdmins, 'email');
    await this.log(`Seeded ${hotelAdmins.length} hotel admin(s)`);
  }
}